# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eduardo/Desktop/Utec/2020-01/algoritmos/presentaciones/presentacion1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eduardo/Desktop/Utec/2020-01/algoritmos/presentaciones/presentacion1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduardo/Desktop/Utec/2020-01/algoritmos/presentaciones/presentacion1/CMakeFiles /home/eduardo/Desktop/Utec/2020-01/algoritmos/presentaciones/presentacion1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduardo/Desktop/Utec/2020-01/algoritmos/presentaciones/presentacion1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IntroSort

# Build rule for target.
IntroSort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IntroSort
.PHONY : IntroSort

# fast build rule for target.
IntroSort/fast:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/build
.PHONY : IntroSort/fast

heapSort.o: heapSort.cpp.o

.PHONY : heapSort.o

# target to build an object file
heapSort.cpp.o:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/heapSort.cpp.o
.PHONY : heapSort.cpp.o

heapSort.i: heapSort.cpp.i

.PHONY : heapSort.i

# target to preprocess a source file
heapSort.cpp.i:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/heapSort.cpp.i
.PHONY : heapSort.cpp.i

heapSort.s: heapSort.cpp.s

.PHONY : heapSort.s

# target to generate assembly for a file
heapSort.cpp.s:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/heapSort.cpp.s
.PHONY : heapSort.cpp.s

insertionSort.o: insertionSort.cpp.o

.PHONY : insertionSort.o

# target to build an object file
insertionSort.cpp.o:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/insertionSort.cpp.o
.PHONY : insertionSort.cpp.o

insertionSort.i: insertionSort.cpp.i

.PHONY : insertionSort.i

# target to preprocess a source file
insertionSort.cpp.i:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/insertionSort.cpp.i
.PHONY : insertionSort.cpp.i

insertionSort.s: insertionSort.cpp.s

.PHONY : insertionSort.s

# target to generate assembly for a file
insertionSort.cpp.s:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/insertionSort.cpp.s
.PHONY : insertionSort.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/main.cpp.s
.PHONY : main.cpp.s

quickSort.o: quickSort.cpp.o

.PHONY : quickSort.o

# target to build an object file
quickSort.cpp.o:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/quickSort.cpp.o
.PHONY : quickSort.cpp.o

quickSort.i: quickSort.cpp.i

.PHONY : quickSort.i

# target to preprocess a source file
quickSort.cpp.i:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/quickSort.cpp.i
.PHONY : quickSort.cpp.i

quickSort.s: quickSort.cpp.s

.PHONY : quickSort.s

# target to generate assembly for a file
quickSort.cpp.s:
	$(MAKE) -f CMakeFiles/IntroSort.dir/build.make CMakeFiles/IntroSort.dir/quickSort.cpp.s
.PHONY : quickSort.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... IntroSort"
	@echo "... edit_cache"
	@echo "... heapSort.o"
	@echo "... heapSort.i"
	@echo "... heapSort.s"
	@echo "... insertionSort.o"
	@echo "... insertionSort.i"
	@echo "... insertionSort.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... quickSort.o"
	@echo "... quickSort.i"
	@echo "... quickSort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

